vim.keymap.set("n", "<F5>", ":Automaton launch default<CR>", {silent = true})
vim.keymap.set("n", "<F6>", ":Automaton debug default<CR>", {silent = true})
vim.keymap.set("n", "<F8>", ":Automaton tasks default<CR>", {silent = true})

vim.keymap.set("n", "<leader>aC", ":Automaton create<CR>", {silent = true})
vim.keymap.set("n", "<leader>aI", ":Automaton init<CR>", {silent = true})
vim.keymap.set("n", "<leader>aL", ":Automaton load<CR>", {silent = true})

vim.keymap.set("n", "<leader>ac", ":Automaton config<CR>", {silent = true})
vim.keymap.set("n", "<leader>ar", ":Automaton recents<CR>", {silent = true})
vim.keymap.set("n", "<leader>aw", ":Automaton workspaces<CR>", {silent = true})
vim.keymap.set("n", "<leader>aj", ":Automaton jobs<CR>", {silent = true})
vim.keymap.set("n", "<leader>al", ":Automaton launch<CR>", {silent = true})
vim.keymap.set("n", "<leader>ad", ":Automaton debug<CR>", {silent = true})
vim.keymap.set("n", "<leader>at", ":Automaton tasks<CR>", {silent = true})

vim.keymap.set("n", "<leader>aol", ":Automaton open launch<CR>", {silent = true})
vim.keymap.set("n", "<leader>aov", ":Automaton open variables<CR>", {silent = true})
vim.keymap.set("n", "<leader>aot", ":Automaton open tasks<CR>", {silent = true})
vim.keymap.set("n", "<leader>aoc", ":Automaton open config<CR>", {silent = true})

vim.keymap.set("v", "<F5>", ":<C-U>Automaton launch default<CR>", {silent = true})
vim.keymap.set("v", "<F6>", ":<C-U>Automaton debug default<CR>", {silent = true})
vim.keymap.set("v", "<F8>", ":<C-U>Automaton tasks default<CR>", {silent = true})
vim.keymap.set("v", "<leader>al", ":<C-U>Automaton launch<CR>", {silent = true})
vim.keymap.set("v", "<leader>ad", ":<C-U>Automaton debug<CR>", {silent = true})
vim.keymap.set("v", "<leader>at", ":<C-U>Automaton tasks<CR>", {silent = true})
